/*
 * This file is generated by jOOQ.
 */
package com.firsttouch.ktl.tables.records;


import com.firsttouch.ktl.tables.Record;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecordRecord extends UpdatableRecordImpl<RecordRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>app.record.id</code>.
     */
    public RecordRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>app.record.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>app.record.FirstName</code>.
     */
    public RecordRecord setFirstname(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>app.record.FirstName</code>.
     */
    public String getFirstname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>app.record.LastName</code>.
     */
    public RecordRecord setLastname(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>app.record.LastName</code>.
     */
    public String getLastname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>app.record.Phone</code>.
     */
    public RecordRecord setPhone(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>app.record.Phone</code>.
     */
    public String getPhone() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Record.RECORD.ID;
    }

    @Override
    public Field<String> field2() {
        return Record.RECORD.FIRSTNAME;
    }

    @Override
    public Field<String> field3() {
        return Record.RECORD.LASTNAME;
    }

    @Override
    public Field<String> field4() {
        return Record.RECORD.PHONE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFirstname();
    }

    @Override
    public String component3() {
        return getLastname();
    }

    @Override
    public String component4() {
        return getPhone();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFirstname();
    }

    @Override
    public String value3() {
        return getLastname();
    }

    @Override
    public String value4() {
        return getPhone();
    }

    @Override
    public RecordRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public RecordRecord value2(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public RecordRecord value3(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public RecordRecord value4(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public RecordRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecordRecord
     */
    public RecordRecord() {
        super(Record.RECORD);
    }

    /**
     * Create a detached, initialised RecordRecord
     */
    public RecordRecord(Integer id, String firstname, String lastname, String phone) {
        super(Record.RECORD);

        setId(id);
        setFirstname(firstname);
        setLastname(lastname);
        setPhone(phone);
    }

    /**
     * Create a detached, initialised RecordRecord
     */
    public RecordRecord(com.firsttouch.ktl.tables.pojos.Record value) {
        super(Record.RECORD);

        if (value != null) {
            setId(value.getId());
            setFirstname(value.getFirstname());
            setLastname(value.getLastname());
            setPhone(value.getPhone());
        }
    }
}
