/*
 * This file is generated by jOOQ.
 */
package com.firsttouch.ktl.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String  address;
    private final String  city;

    public Address(Address value) {
        this.id = value.id;
        this.address = value.address;
        this.city = value.city;
    }

    public Address(
        Integer id,
        String  address,
        String  city
    ) {
        this.id = id;
        this.address = address;
        this.city = city;
    }

    /**
     * Getter for <code>app.address.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>app.address.Address</code>.
     */
    public String getAddress() {
        return this.address;
    }

    /**
     * Getter for <code>app.address.City</code>.
     */
    public String getCity() {
        return this.city;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Address (");

        sb.append(id);
        sb.append(", ").append(address);
        sb.append(", ").append(city);

        sb.append(")");
        return sb.toString();
    }
}
