/*
 * This file is generated by jOOQ.
 */
package com.firsttouch.ktl;


import com.firsttouch.ktl.tables.Address;
import com.firsttouch.ktl.tables.Addresstorecord;
import com.firsttouch.ktl.tables.Record;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class App extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>app</code>
     */
    public static final App APP = new App();

    /**
     * The table <code>app.address</code>.
     */
    public final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>app.addresstorecord</code>.
     */
    public final Addresstorecord ADDRESSTORECORD = Addresstorecord.ADDRESSTORECORD;

    /**
     * The table <code>app.record</code>.
     */
    public final Record RECORD = Record.RECORD;

    /**
     * No further instances allowed
     */
    private App() {
        super("app", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Address.ADDRESS,
            Addresstorecord.ADDRESSTORECORD,
            Record.RECORD
        );
    }
}
