/*
 * This file is generated by jOOQ.
 */
package com.firsttouch.ktl;


import com.firsttouch.ktl.tables.Addresstorecord;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in app.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADDRESSTORECORD_ADDRESS_IDX = Internal.createIndex(DSL.name("address_idx"), Addresstorecord.ADDRESSTORECORD, new OrderField[] { Addresstorecord.ADDRESSTORECORD.ADDRESSID }, false);
    public static final Index ADDRESSTORECORD_RECORD_IDX = Internal.createIndex(DSL.name("record_idx"), Addresstorecord.ADDRESSTORECORD, new OrderField[] { Addresstorecord.ADDRESSTORECORD.RECORDID }, false);
}
