/*
 * This file is generated by jOOQ.
 */
package com.firsttouch.ktl;


import com.firsttouch.ktl.tables.Address;
import com.firsttouch.ktl.tables.Addresstorecord;
import com.firsttouch.ktl.tables.Record;
import com.firsttouch.ktl.tables.records.AddressRecord;
import com.firsttouch.ktl.tables.records.AddresstorecordRecord;
import com.firsttouch.ktl.tables.records.RecordRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in app.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AddressRecord> KEY_ADDRESS_PRIMARY = Internal.createUniqueKey(Address.ADDRESS, DSL.name("KEY_address_PRIMARY"), new TableField[] { Address.ADDRESS.ID }, true);
    public static final UniqueKey<AddresstorecordRecord> KEY_ADDRESSTORECORD_PRIMARY = Internal.createUniqueKey(Addresstorecord.ADDRESSTORECORD, DSL.name("KEY_addresstorecord_PRIMARY"), new TableField[] { Addresstorecord.ADDRESSTORECORD.ID, Addresstorecord.ADDRESSTORECORD.RECORDID }, true);
    public static final UniqueKey<RecordRecord> KEY_RECORD_PRIMARY = Internal.createUniqueKey(Record.RECORD, DSL.name("KEY_record_PRIMARY"), new TableField[] { Record.RECORD.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AddresstorecordRecord, AddressRecord> ADDRESS = Internal.createForeignKey(Addresstorecord.ADDRESSTORECORD, DSL.name("address"), new TableField[] { Addresstorecord.ADDRESSTORECORD.ADDRESSID }, Keys.KEY_ADDRESS_PRIMARY, new TableField[] { Address.ADDRESS.ID }, true);
    public static final ForeignKey<AddresstorecordRecord, RecordRecord> RECORD = Internal.createForeignKey(Addresstorecord.ADDRESSTORECORD, DSL.name("record"), new TableField[] { Addresstorecord.ADDRESSTORECORD.RECORDID }, Keys.KEY_RECORD_PRIMARY, new TableField[] { Record.RECORD.ID }, true);
}
